### ISSUE TITLE
Rename the constans

### ISSUE THREAD

**Issue by j-a-m-l** [ArkEcosystem/ruby-client#12]
Instead of using `ArkClient::API::Two::Peers`, use `ArkClient::API::V2::Peers` or `ArkClient::V2::Peers`.

Other idea is using `Ark::Client::V2::Peers`. On the `ruby-crypto` repo, it'd be something like `Ark::Crypto::TransactionBuilder` or `Ark::TransactionBuilder`.

What do you think @faustbrian ?

**Comment by faustbrian** [comment]
The packages are now available under `ArkEcosystem::Crypto` and `ArkEcosystem::Client`.

**Comment by j-a-m-l** [comment]
And what about using `ArkEcosystem::Client::V1::Peers` instead of `ArkEcosystem::Client::API::One::Peers`?

**Comment by j-a-m-l** [comment]
And, what about `ArkEcosystem::Client::API::V1::Peers`? It's much more concise and clear.
